language: node_js
sudo: required
services:
  - docker
os:
  - linux
  - osx
osx_image: xcode9.3
install:
  - export PREBUILD_SLUG=$TRAVIS_REPO_SLUG
  - export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig" #node-gfx/node-canvas-prebuilt#76
  - >- # this should only run on linux
    if [ $TRAVIS_OS_NAME = "linux" ]; then

    docker build -t canvas-musl-prebuilt:latest -f docker/Dockerfile.musl .;
    docker run
    -e PREBUILD_VERSION="$PREBUILD_VERSION"
    -e PREBUILD_AUTH="$PREBUILD_AUTH"
    -e PREBUILD_SLUG="$TRAVIS_REPO_SLUG"
    -e PREBUILD_NODE_VERSIONS="$PREBUILD_NODE_VERSIONS"
    -v $(pwd):/build canvas-musl-prebuilt:latest
    bash -c 'cd /build; export NVM_DIR=$HOME/.nvm; . $HOME/.nvm/nvm.sh; . ci/install.sh linux '"\"$PREBUILD_VERSION\" \"$PREBUILD_CANVAS_VERSION\" \"$PREBUILD_NODE_VERSIONS\"";

    docker run
    -e PREBUILD_VERSION="$PREBUILD_VERSION"
    -e PREBUILD_AUTH="$PREBUILD_AUTH"
    -e PREBUILD_SLUG="$TRAVIS_REPO_SLUG"
    -e PREBUILD_NODE_VERSIONS="$PREBUILD_NODE_VERSIONS"
    -v $(pwd):/build chearon/canvas-prebuilt:7
    bash -c 'cd /build; export NVM_DIR=$HOME/.nvm; . $HOME/.nvm/nvm.sh; . ci/install.sh linux '"\"$PREBUILD_VERSION\" \"$PREBUILD_CANVAS_VERSION\" \"$PREBUILD_NODE_VERSIONS\"";

    else

    export PREBUILD_SLUG="$TRAVIS_REPO_SLUG";

    bash ci/install.sh osx "$PREBUILD_VERSION" "$PREBUILD_CANVAS_VERSION" "$PREBUILD_NODE_VERSIONS";

    fi
